# Análisis Exploratorio de Datos (EDA) – 20 Preguntas y Preguntas de Negocio

En este notebook se plantean 20 preguntas que combinan operaciones de filtrado y agrupación sobre el dataset de ventas de Adidas en EE.UU. Además, se incluyen preguntas de negocio para que los estudiantes deban abstraer y razonar sobre las implicaciones comerciales de los datos.

El ejercicio abarca:
- Análisis descriptivo básico (dimensiones, unidades de observación).
- Cálculo de totales, promedios y márgenes.
- Agrupaciones por Retailer, Estado, Producto y Método de Venta.
- Filtrados para extraer subconjuntos de datos.
- Preguntas de negocio para interpretar resultados y proponer soluciones basadas en la información.

¡Comienza resolviendo cada punto y analizando los resultados obtenidos!

In [2]:
wget https://github.com/prayagpadwal/Adidas-Sales-An!alysis/raw/main/Adidas%20US%20Sales%20Datasets.xlsx

--2025-03-13 19:37:28--  https://github.com/prayagpadwal/Adidas-Sales-Analysis/raw/main/Adidas%20US%20Sales%20Datasets.xlsx
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/prayagpadwal/Adidas-Sales-Analysis/main/Adidas%20US%20Sales%20Datasets.xlsx [following]
--2025-03-13 19:37:28--  https://raw.githubusercontent.com/prayagpadwal/Adidas-Sales-Analysis/main/Adidas%20US%20Sales%20Datasets.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 693038 (677K) [application/octet-stream]
Saving to: ‘Adidas US Sales Datasets.xlsx’

Adidas US Sales Dat 100%[===================>] 676.79K  --.-KB/s    in 0.06s

2025-03-13 19:37:28 (11.8 MB/s) - ‘Adidas US Sales Datasets.xlsx’ saved [693038/693038]

In [3]:
# Importar librerías necesarias
import pandas as pd
import numpy as np

# Leer el archivo Excel (asegúrate de haber subido 'Adidas US Sales Datasets.xlsx' a tu entorno de Colab)
data = pd.read_excel('Adidas US Sales Datasets.xlsx')

## Pregunta 1
**¿Cuántas filas y columnas tiene el dataset?**

_Muestra las dimensiones del DataFrame._

In [4]:
data.shape

(9648, 13)

## Pregunta 2
**¿Cuál es la unidad de observación del dataset?**

_Describe qué representa cada fila (por ejemplo, una transacción o venta individual)._

In [5]:
data.head()
# Esta a nivel de productos vendidos y retailers

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store

## Pregunta 3
**¿Cuáles fueron las ventas totales?**

_Suma de la columna 'Total Sales'._

In [6]:
data['Total Sales'].sum()

899902125.0

## Pregunta 4
**¿Cuál fue la ganancia operativa total?**

_Suma de la columna 'Operating Profit'._

In [7]:
data['Operating Profit'].sum()

332134761.45000005

## Pregunta 5
**¿Cuál es el margen operativo promedio?**

_Calcula la media de la columna 'Operating Margin' y explica por qué se utiliza el promedio en lugar de una suma._

In [8]:
# Porque estos pueden variar mes a mes y para tener un resultado más significativo se debe hacer un promedio de estas

data['Operating Margin'].mean()

0.42299129353233833

## Pregunta 6
**Agrupar por Retailer y calcular:**
- La suma de 'Total Sales'
- La suma de 'Operating Profit'
- La suma de 'Units Sold'

_Utiliza `groupby` para obtener estos totales por cada Retailer._

In [9]:
review_retailer = data.groupby('Retailer').agg({'Total Sales': 'sum', 'Operating Profit': 'sum', 'Units Sold': 'sum'})

print(review_retailer)

               Total Sales  Operating Profit  Units Sold
Retailer
Amazon          77698912.0       28818503.31      197990
Foot Locker    220094720.0       80722124.81      604369
Kohl's         102114753.0       36811252.58      287375
Sports Direct  182470997.0       74332954.96      557640
Walmart         74558410.0       25782052.61      206225
West Gear      242964333.0       85667873.18      625262

In [10]:
review_retailer1 = data.groupby('Retailer')[['Total Sales','Operating Profit','Units Sold']].sum()
print(review_retailer1)

               Total Sales  Operating Profit  Units Sold
Retailer
Amazon          77698912.0       28818503.31      197990
Foot Locker    220094720.0       80722124.81      604369
Kohl's         102114753.0       36811252.58      287375
Sports Direct  182470997.0       74332954.96      557640
Walmart         74558410.0       25782052.61      206225
West Gear      242964333.0       85667873.18      625262

## Pregunta 7
**Calcular el margen total por Retailer y el margen operativo promedio por Retailer.**

- Margen total: (Suma de 'Operating Profit' / Suma de 'Total Sales') por Retailer.
- Margen promedio: Promedio de la columna 'Operating Margin' para cada Retailer.

_Compara ambos resultados y comenta la diferencia, reflexionando sobre el significado en términos de negocio._

In [11]:
#Calcular los totales por Retailer (Review retailer)
review_retailer = data.groupby('Retailer').agg({'Total Sales': 'sum', 'Operating Profit': 'sum', 'Units Sold': 'sum'})

#Calcular el margen total por Retailer
review_retailer['Margin Total'] = review_retailer['Operating Profit'] / review_retailer['Total Sales']

#Calcular el margen operativo por Retailer
retailer_averages = data.groupby('Retailer')['Operating Margin'].mean()

retailer_averages = retailer_averages.rename('Margen Operativo Promedio')

# Combinar los resultados en un solo Dataframe
retailer_margins = pd.concat([review_retailer, retailer_averages], axis=1)

print(retailer_margins)

               Total Sales  Operating Profit  Units Sold  Margin Total  \
Retailer
Amazon          77698912.0       28818503.31      197990      0.370900
Foot Locker    220094720.0       80722124.81      604369      0.366761
Kohl's         102114753.0       36811252.58      287375      0.360489
Sports Direct  182470997.0       74332954.96      557640      0.407369
Walmart         74558410.0       25782052.61      206225      0.345797
West Gear      242964333.0       85667873.18      625262      0.352594

               Margen Operativo Promedio
Retailer
Amazon                          0.417871
Foot Locker                     0.417933
Kohl's                          0.419291
Sports Direct                   0.444892
Walmart                         0.406534
West Gear                       0.417856

## Pregunta 8
**¿Qué Retailer vendió la mayor cantidad de unidades totales?**

_Agrupa por Retailer, suma 'Units Sold' y ordena de forma descendente._

In [12]:
# prompt: ¿Qué Retailer vendió la mayor cantidad de unidades totales?
# Agrupa por Retailer, suma 'Units Sold' y ordena de forma descendente.

# Agrupa por Retailer, suma 'Units Sold' y ordena de forma descendente.
top_retailer = data.groupby('Retailer')['Units Sold'].sum().sort_values(ascending=False)

print(top_retailer)
print(f"\nEl Retailer que más unidades vendió es: {top_retailer.index[0]}")

Retailer
West Gear        625262
Foot Locker      604369
Sports Direct    557640
Kohl's           287375
Walmart          206225
Amazon           197990
Name: Units Sold, dtype: int64

El Retailer que más unidades vendió es: West Gear

## Pregunta 9
**¿Qué producto vendió la mayor cantidad de unidades?**

_Agrupa por 'Product' y suma 'Units Sold' para identificar el producto líder._

In [13]:
data.groupby('Product').max()

,Retailer,Retailer ID,Invoice Date,Region,State,City,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
Product,,,,,,,,,,,,
Men's Apparel,West Gear,1197831,2021-12-31,West,Wyoming,Wilmington,95.0,925,617500.0,281250.0,0.77,Outlet
Men's Athletic Footwear,West Gear,1197831,2021-12-28,West,Wyoming,Wilmington,95.0,1025,712500.0,285000.0,0.65,Outlet
Men's Street Footwear,West Gear,1197831,2021-12-27,West,Wyoming,Wilmington,95.0,1275,810000.0,390000.0,0.70,Outlet
Women's Apparel,West Gear,1197831,2021-12-26,West,Wyoming,Wilmington,110.0,1100,825000.0,371250.0,0.80,Outlet
Women's Athletic Footwear,West Gear,1197831,2021-12-30,West,Wyoming,Wilmington,90.0,925,540000.0,216000.0,0.75,Outlet
Women's Street Footwear,West Gear,1197831,2021-12-29,West,Wyoming,Wilmington,95.0,1100,665000.0,266000.0,0.64,Outlet

## Pregunta 10
**Agrupar por el método de venta ('Sales Method') y calcular:**
- La suma de 'Total Sales'
- El promedio de 'Total Sales'

_Esta agrupación ayudará a identificar cuál método tiene mejores resultados en términos de volumen y eficiencia._

In [14]:
data.groupby('Sales Method')['Total Sales'].agg(['sum', 'mean'])

                      sum           mean
Sales Method
In-store      356643750.0  204967.672414
Online        247672882.0   50659.210882
Outlet        295585493.0   97908.411063

## Pregunta 11
**¿Qué método de venta tiene mayores ventas totales y mayores ventas promedio?**

_Analiza los resultados obtenidos en la Pregunta 10 y comenta posibles razones de negocio detrás de estos resultados._

Las ventas totales con mejores indicadoes son las ventas en tiendas fisicas

## Pregunta 12
**Agrupar por State y calcular la suma de 'Total Sales'.**

_Determina cuál es el estado con mayores ventas totales._

In [15]:
 data.groupby('State')['Total Sales'].sum()

State
Alabama           17633424.0
Alaska            14753103.0
Arizona           15782221.0
Arkansas          12639347.0
California        60174133.0
Colorado          20996536.0
Connecticut       11573448.0
Delaware          12298412.0
Florida           59283714.0
Georgia           18997466.0
Hawaii            22282457.0
Idaho             19276878.0
Illinois           9797488.0
Indiana            8836198.0
Iowa               7424011.0
Kansas             9972864.0
Kentucky          10072848.0
Louisiana         23750781.0
Maine              9195978.0
Maryland           7758059.0
Massachusetts     11076810.0
Michigan          18625433.0
Minnesota          7378068.0
Mississippi       15591709.0
Missouri           9683265.0
Montana           15710886.0
Nebraska           5929038.0
Nevada            20858509.0
New Hampshire     16411667.0
New Jersey         9934246.0
New Mexico        19865016.0
New York          64229039.0
North Carolina    23956531.0
North Dakota       7735580.0
Ohio              18484583.0
Oklahoma          10620734.0
Oregon            21349674.0
Pennsylvania      10357519.0
Rhode Island       8446806.0
South Carolina    29285637.0
South Dakota       8495576.0
Tennessee         18067440.0
Texas             46359746.0
Utah               9696420.0
Vermont           14352923.0
Virginia          21575040.0
Washington        26330718.0
West Virginia     10689160.0
Wisconsin          7727469.0
Wyoming           18577517.0
Name: Total Sales, dtype: float64

In [16]:
ventas_por_estado = data.groupby('State')['Total Sales'].sum()
estado_mayores_ventas = ventas_por_estado.idxmax()
print(f"El estado con mayores ventas totales es: {estado_mayores_ventas}")

El estado con mayores ventas totales es: New York

## Pregunta 13 (Negocio)
**¿Qué estado muestra un mejor desempeño operativo?**

_Agrupa por State y calcula el promedio de 'Operating Margin' para evaluar cuál estado opera de manera más eficiente. Comenta posibles implicaciones de negocio._

In [17]:

state_operating_margin = data.groupby('State')['Operating Margin'].mean()
best_performing_state = state_operating_margin.idxmax()
print(f"El estado con mejor desempeño operativo es: {best_performing_state}")
print("\nMárgenes operativos promedio por estado:")
print(state_operating_margin)

El estado con mejor desempeño operativo es: Alabama

Márgenes operativos promedio por estado:
State
Alabama           0.553565
Alaska            0.349861
Arizona           0.389815
Arkansas          0.440509
California        0.386852
Colorado          0.427083
Connecticut       0.401620
Delaware          0.427986
Florida           0.390222
Georgia           0.413704
Hawaii            0.319583
Idaho             0.458935
Illinois          0.449514
Indiana           0.433889
Iowa              0.420903
Kansas            0.411667
Kentucky          0.448611
Louisiana         0.446852
Maine             0.398889
Maryland          0.407431
Massachusetts     0.347130
Michigan          0.475764
Minnesota         0.408125
Mississippi       0.454306
Missouri          0.453194
Montana           0.471042
Nebraska          0.457917
Nevada            0.405926
New Hampshire     0.391019
New Jersey        0.427083
New Mexico        0.392917
New York          0.408333
North Carolina    0.463542
North Dakota      0.398611
Ohio              0.459028
Oklahoma          0.435093
Oregon            0.413611
Pennsylvania      0.425880
Rhode Island      0.412361
South Carolina    0.433056
South Dakota      0.394653
Tennessee         0.506574
Texas             0.449144
Utah              0.444676
Vermont           0.444259
Virginia          0.414398
Washington        0.325069
West Virginia     0.456806
Wisconsin         0.424236
Wyoming           0.402778
Name: Operating Margin, dtype: float64

## Pregunta 14
**Filtro 1: Crea un DataFrame filtrado para el Retailer con mayores ventas totales.**

_Utiliza la agrupación previa para identificar dicho Retailer y filtra el dataset original._

In [18]:

retailer_ventas = data.groupby('Retailer')['Total Sales'].sum()
top_retailer = retailer_ventas.idxmax()
df_filtrado = data[data['Retailer'] == top_retailer]

df_filtrado

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
140,West Gear,1128299,2020-11-01,South,Texas,Houston,Men's Street Footwear,40.0,775,310000.0,108500.00,0.35,Outlet
141,West Gear,1128299,2020-11-02,South,Texas,Houston,Men's Athletic Footwear,50.0,775,387500.0,77500.00,0.20,Outlet
142,West Gear,1128299,2020-11-03,South,Texas,Houston,Women's Street Footwear,50.0,775,387500.0,135625.00,0.35,Outlet
143,West Gear,1128299,2020-11-04,South,Texas,Houston,Women's Athletic Footwear,50.0,625,312500.0,93750.00,0.30,Outlet
144,West Gear,1128299,2020-11-05,West,California,San Francisco,Men's Apparel,55.0,575,316250.0,158125.00,0.50,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9265,West Gear,1197831,2021-10-21,South,Oklahoma,Oklahoma City,Men's Apparel,22.0,68,1496.0,568.48,0.38,Outlet
9554,West Gear,1185732,2021-10-12,Northeast,Vermont,Burlington,Women's Apparel,54.0,90,4860.0,2235.60,0.46,Outlet
9555,West Gear,1185732,2021-11-11,Northeast,Vermont,Burlington,Men's Street Footwear,54.0,140,7560.0,3780.00,0.50,Outlet
9556,West Gear,1185732,2021-11-11,Northeast,Vermont,Burlington,Men's Athletic Footwear,47.0,98,4606.0,2256.94,0.49,Outlet
9557,West Gear,1185732,2021-11-11,Northeast,Vermont,Burlington,Women's Street Footwear,46.0,102,4692.0,1736.04,0.37,Outlet

## Pregunta 15
**Filtro 2: Crea un DataFrame filtrado para el estado con mayores ventas totales.**

_Utiliza la agrupación por State para identificar dicho estado y filtra el dataset original._

In [19]:
ventas_por_estado = data.groupby('State')['Total Sales'].sum()
estado_mayores_ventas = ventas_por_estado.idxmax()
df_filtrado_estado = data[data['State'] == estado_mayores_ventas]
df_filtrado_estado

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7843,Walmart,1185732,2020-07-18,Northeast,New York,New York,Women's Apparel,48.0,340,16320.0,4896.00,0.30,Outlet
7844,Sports Direct,1197831,2020-07-19,Northeast,New York,New York,Men's Street Footwear,20.0,270,5400.0,2106.00,0.39,Outlet
7845,Sports Direct,1197831,2020-07-20,Northeast,New York,New York,Men's Athletic Footwear,26.0,270,7020.0,2597.40,0.37,Outlet
7846,Sports Direct,1197831,2020-07-21,Northeast,New York,New York,Women's Street Footwear,27.0,238,6426.0,2506.14,0.39,Outlet
7847,Sports Direct,1197831,2020-07-22,Northeast,New York,New York,Women's Athletic Footwear,27.0,210,5670.0,2948.40,0.52,Outlet

## Pregunta 16
**Filtro 3: Crea un DataFrame filtrado para el producto con mayor cantidad de unidades vendidas.**

_Identifica el producto líder y extrae las transacciones relacionadas._

In [20]:

product_sales = data.groupby('Product')['Units Sold'].sum()
top_product = product_sales.idxmax()
df_filtrado_producto = data[data['Product'] == top_product]
df_filtrado_producto

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
6,Foot Locker,1185732,2020-01-07,Northeast,New York,New York,Men's Street Footwear,50.0,1250,625000.0,312500.00,0.50,In-store
12,Foot Locker,1185732,2020-01-25,Northeast,New York,New York,Men's Street Footwear,50.0,1220,610000.0,305000.00,0.50,Outlet
18,Foot Locker,1185732,2020-01-31,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,Outlet
24,Foot Locker,1185732,2020-02-06,Northeast,New York,New York,Men's Street Footwear,60.0,1220,732000.0,366000.00,0.50,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9621,Foot Locker,1185732,2021-10-19,Northeast,New Hampshire,Manchester,Men's Street Footwear,52.0,162,8424.0,3538.08,0.42,Outlet
9627,Foot Locker,1185732,2021-11-18,Northeast,New Hampshire,Manchester,Men's Street Footwear,59.0,149,8791.0,3780.13,0.43,Outlet
9633,Foot Locker,1185732,2021-12-17,Northeast,New Hampshire,Manchester,Men's Street Footwear,49.0,200,9800.0,4606.00,0.47,Outlet
9639,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Street Footwear,36.0,165,5940.0,2197.80,0.37,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet

## Pregunta 17 (Negocio)
**¿Qué Retailer presenta el mayor margen operativo y por qué podría ser significativo desde el punto de vista del negocio?**

_Analiza el resumen por Retailer y discute las posibles implicaciones (por ejemplo, eficiencia operativa, estrategia de precios, etc.)._

In [21]:
retailer_operating_margin = data.groupby('Retailer')['Operating Margin'].mean()
top_retailer_margin = retailer_operating_margin.idxmax()
print(f"El Retailer con el mayor margen operativo es: {top_retailer_margin}")
print("\nMargen operativo promedio por Retailer:")
print(retailer_operating_margin)

El Retailer con el mayor margen operativo es: Sports Direct

Margen operativo promedio por Retailer:
Retailer
Amazon           0.417871
Foot Locker      0.417933
Kohl's           0.419291
Sports Direct    0.444892
Walmart          0.406534
West Gear        0.417856
Name: Operating Margin, dtype: float64

El retailer con el mayor margen operativo es (Sports direct)

## Pregunta 18 (Negocio)
**Analiza el desempeño entre métodos de venta (por ejemplo, In-store vs. Online si aplica).**

_Si el dataset incluye ambos métodos, comenta sobre las posibles diferencias en ventas totales y promedios y qué implicaciones podrían tener en la estrategia comercial._

In [22]:
sales_method_analysis = data.groupby('Sales Method')['Total Sales'].agg(['sum', 'mean'])
sales_method_analysis = sales_method_analysis.rename(
    columns={'sum': 'Total Sales', 'mean': 'Average Sales'}
)
print(sales_method_analysis)

              Total Sales  Average Sales
Sales Method
In-store      356643750.0  204967.672414
Online        247672882.0   50659.210882
Outlet        295585493.0   97908.411063

## Pregunta 19
**Filtro Combinado: Crea un DataFrame filtrado que cumpla con los siguientes criterios:**
- Retailer con mayores ventas totales
- Estado con mayores ventas totales
- Producto con mayor cantidad de unidades vendidas
- Método de venta con mayores ventas totales

_Muestra las primeras filas del DataFrame resultante._

In [23]:
retailer_ventas = data.groupby('Retailer')['Total Sales'].sum()
top_retailer = retailer_ventas.idxmax()
ventas_por_estado = data.groupby('State')['Total Sales'].sum()
estado_mayores_ventas = ventas_por_estado.idxmax()
product_sales = data.groupby('Product')['Units Sold'].sum()
top_product = product_sales.idxmax()
sales_method_sales = data.groupby('Sales Method')['Total Sales'].sum()
top_sales_method = sales_method_sales.idxmax()
df_filtrado_combinado = data[
    (data['Retailer'] == top_retailer) &
    (data['State'] == estado_mayores_ventas) &
    (data['Product'] == top_product) &
    (data['Sales Method'] == top_sales_method)
]
print(df_filtrado_combinado.head())

       Retailer  Retailer ID Invoice Date     Region     State    City  \
1443  West Gear      1185732   2021-03-08  Northeast  New York  Albany
1449  West Gear      1185732   2021-04-09  Northeast  New York  Albany
1455  West Gear      1185732   2021-05-08  Northeast  New York  Albany
1461  West Gear      1185732   2021-06-10  Northeast  New York  Albany
1467  West Gear      1185732   2021-07-08  Northeast  New York  Albany

                    Product  Price per Unit  Units Sold  Total Sales  \
1443  Men's Street Footwear            45.0         870     391500.0
1449  Men's Street Footwear            45.0         825     371250.0
1455  Men's Street Footwear            55.0         870     478500.0
1461  Men's Street Footwear            60.0         875     525000.0
1467  Men's Street Footwear            65.0         950     617500.0

      Operating Profit  Operating Margin Sales Method
1443          176175.0              0.45     In-store
1449          167062.5              0.45     In-store
1455          215325.0              0.45     In-store
1461          236250.0              0.45     In-store
1467          277875.0              0.45     In-store

## Pregunta 20 (Negocio)
**Basado en el análisis de las variables (ventas, margen, unidades vendidas) y la matriz de correlación (si se llegase a calcular en un análisis posterior), ¿cuáles crees que son los principales factores que contribuyen a la ganancia operativa?**

_Esta pregunta es abierta: reflexiona sobre la relación entre precio por unidad, unidades vendidas, ventas totales y margen operativo, y plantea posibles estrategias de negocio basadas en estos insights._

Los elementos clave que favorecen el beneficio operacional son un equilibrio apropiado entre el precio por unidad, las unidades comercializadas y el margen de beneficio operativo. Incrementar las unidades comercializadas, conservar o incrementar el margen por unidad y optimizar los costos de operación son fundamentales para incrementar al máximo las ganancias. Las tácticas empresariales deben centrarse en hallar un balance entre volumen y precio, maximizar los gastos y brindar valor a los clientes para garantizar una rentabilidad duradera.

## Conclusión

En este notebook se han planteado 20 preguntas que combinan análisis técnico y reflexiones de negocio. Se ha trabajado con filtrados y agrupaciones para extraer insights clave del dataset de ventas, lo que permite a los estudiantes practicar y comprender cómo los datos pueden informar decisiones estratégicas en un entorno comercial.